theme: minima
title: Sandy Cadet
description: Academic portfolio highlighting my interdisciplinary academic portfolio exploring biological sciences coursework, medicical and scientific interests, astrophysics technical skills and leadership.
author: Sandy Cadet
